server:
  servlet:
    context-path: ${CONTEXT_PATH}
  port: ${SERVER_PORT:8080}

app:
  async:
    core-pool-size: ${CORE_POOL_SIZE:2}
    max-pool-size: ${MAX_POOL_SIZE:4}
    queue-capacity: ${QUEUE_CAPACITY:40}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always